// Generated by CoffeeScript 1.9.0
var odd, odd2;

odd = function(num) {
  if (typeof num === 'number') {
    if (num === Math.round(num)) {
      if (num > 0) {
        return num % 2 === 1;
      } else {
        throw num + "는 양수가 아니다.";
      }
    } else {
      throw num + "는 정수가 아니다.";
    }
  } else {
    throw num + "는 숫자가 아니다.";
  }
};

odd2 = (function(_this) {
  return function(num) {
    if (typeof num !== 'number') {
      throw num + "는 숫자가 아니다.";
    }
    if (num !== Math.round(num)) {
      throw num + "는 정수가 아니다.";
    }
    if (!(num > 0)) {
      throw num + "는 양수가 아니다.";
    }
    return num % 2 === 1;
  };
})(this);
